""" Constants """
BACKUP_DIR = '.b3g'
CONTEND_DIR = "workplace"
OLD_VERSIONS_DIR = "OLD_VERSIONS_DIR"
CONFIG_FILE = ".b3gCONFIG"


""" Constant for the tests """
SOURCE = "file_test1.txt"
FILE_TO_COPY = "file_copied.txt"
FILE_TO_RENAME = "file_test2.txt"
FILE_TO_CREATE = "file_created.txt"
FILE_TO_DELETE = FILE_TO_CREATE
DIR_TO_CREATE ="./DIR_TEST"
DIR_TO_DELETE = DIR_TO_CREATE
FILE_TO_COMPARE1 = SOURCE
FILE_TO_COMPARE2 = FILE_TO_RENAME
DIFF_FILE = "diff.log"
FILE_TO_WRITE = FILE_TO_COPY
FILE_TO_COMPRESS = FILE_TO_RENAME
FILE_TO_DECOMPRESS = FILE_TO_COMPRESS + '.gz'